# Generated by Django 3.1 on 2020-09-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('base_url', models.TextField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('article_link', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('published_date', models.TextField(blank=True, null=True)),
                ('article_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_list',
                'managed': False,
            },
        ),
    ]
